include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml

docker-publish-image-prod:
  extends: .build-image-using-kaniko
  variables:
    CI_REGISTRY_IMAGE: $CI_REGISTRY/$NSE_PROJECT/psp-validation-ui
    REGISTRY_IMAGE_TAG: mooc-bbp
    CI_PROJECT_DIR: /builds/nse/psp-validation-ui/frontend/
    KANIKO_EXTRA_ARGS: --build-arg BUILD_MODE='production'
  rules:
     - if: $CI_COMMIT_BRANCH == "mooc-bbp"

docker-publish-image-dev:
  extends: .build-image-using-kaniko
  variables:
    CI_REGISTRY_IMAGE: $CI_REGISTRY/$NSE_PROJECT/psp-validation-ui
    REGISTRY_IMAGE_TAG: mooc-bbp-dev
    CI_PROJECT_DIR: /builds/nse/psp-validation-ui/frontend/
    KANIKO_EXTRA_ARGS: --build-arg BUILD_MODE='development'
  rules:
     - if: $CI_COMMIT_BRANCH != "mooc-bbp"
